version: "3.8"                                          # 파일 규격 버전
services:                                               # 이 항목 밑에 실행하려는 컨테이너들을 정의
  board-redis:                        # 서비스명
    container_name: board-redis       # 컨테이너 명
    build:
      dockerfile: Dockerfile
      context: ./redis
    image: ds257873/board-redis
    ports:
      - "6380:6379"
  board-database:
    container_name: board-database
    build:
      dockerfile: Dockerfile
      context: ./database
    image: ds257873/board-database
    environment:
      - MARIADB_DATABASE=board
      - MARIADB_ROOT_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - ./database/config:/etc/mysql/conf.d
      - ./database/init:/docker-entrypoint-initdb.d
    ports:
      - "3308:3306"      # 접근 포트 설정 (컨테이너 외부:컨테이너 내부)